<?php
// generate_roles_config.php
// Usage: php source/tools/generate_roles_config.php
// Reads DB using environment variables and writes application/config/roles.php

$host = getenv('DB_HOST') ?: '127.0.0.1';
$user = getenv('DB_USER') ?: 'root';
$pass = getenv('DB_PASS') ?: '';
$name = getenv('DB_NAME') ?: '';
$port = getenv('DB_PORT') ?: 3306;

echo "Connecting to DB $host:$port, database '$name'...\n";
$mysqli = @new mysqli($host, $user, $pass, $name, (int)$port);
if ($mysqli->connect_errno) {
    echo "DB connection failed: (" . $mysqli->connect_errno . ") " . $mysqli->connect_error . "\n";
    exit(1);
}

$result = $mysqli->query("SELECT id, name FROM roles");
if (!$result) {
    echo "Query failed: " . $mysqli->error . "\n";
    exit(1);
}

$map = [];
while ($row = $result->fetch_assoc()) {
    $map[$row['name']] = (int)$row['id'];
}

if (empty($map)) {
    echo "No roles found in 'roles' table.\n";
    exit(1);
}

$export = var_export($map, true);
$cfgPath = __DIR__ . '/../../source/application/config/roles.php';
// normalize path for target in repo
$target = dirname(__FILE__, 3) . '/application/config/roles.php';
$content = "<?php\n// Auto-generated by source/tools/generate_roles_config.php\nreturn $export;\n";

if (file_put_contents($target, $content) === false) {
    echo "Failed to write $target\n";
    exit(1);
}

echo "Wrote roles config to $target\n";
exit(0);
